### ISSUE TITLE
Old version of web-token/jwt-framework 

### ISSUE THREAD

**Issue by KasperFranz** [CyberSource/cybersource-rest-client-php#138]
Hi,

I can see you have just included the package web-token/jwt-framework  in the latest release.

Would you be able to update to use v3 instead of v2? (or allow both at the same time).

version 2 is using  symfony/console ^4.2|^5.0
version 3 allows ^5.4|^6.0.

Symfony 4.4 is out of security support in November this year https://symfony.com/releases/4.4

Thank you

**Comment by KasperFranz** [comment]
Thank you,
We are not able to update our integration as the required package conflicts with our security policy

**Comment by KasperFranz** [comment]
Any update on this?

**Comment by rbhalgami** [comment]
Hi,
Do you have any updates on this? We are unable to integrate one of the packages which is dependent on this.

**Comment by uverus2** [comment]
Any updates on this please ?

**Comment by ms-abm** [comment]
Hi,

We can't update cybersource/rest-client-php (right now locked in 0.0.43) as well because we're using Symfony 6. 

And we have to update before 3/22/2024 due to security fix https://community.developer.cybersource.com/t5/cybersource-Developer-Blog/REST-API-Http-Signature-Authentication-Critical-Security-Update/ba-p/87319

Could you please prioritize that?

**Comment by ms-abm** [comment]
@gaubansa  @monu-kumar-visa  @gnongsie could you please check?

**Comment by jaycruz805** [comment]
Same issue. Downgrading symfony/console is out of the question for us from a security standpoint and also from package conflict standpoint. 

I'm using  "laravel/framework": "^10.10" and PHP 8.2 and there are so many conflicts that arise even if I try to downgrade symphony/console version. 

Similiar issues arise when with  "brick/math" dependency. 

Please fix since Cybersource is requiring developers to upgrade March 22nd 2024 .

**Comment by monu-kumar-visa** [comment]
We've updated the [blog post](https://community.developer.cybersource.com/t5/cybersource-Developer-Blog/REST-API-Http-Signature-Authentication-Critical-Security-Update/ba-p/87319); the updated date is April 22. Additionally, we will share an update regarding the upgrade decision by the end of February.

**Comment by mihani** [comment]
Hello, do we have an update concerning the impossibility to upgrade the package for a symfony/laravel project ?
